### ISSUE TITLE
Translate to spanish

### ISSUE THREAD

**Issue by susobaco** [LubuWest/Friendiqa#1]
Hi, congratulations for your work, I would like to contribute translating the application into Spanish. What files do I have to translate? Thank you

**Comment by LubuWest** [comment]
Thank you for your help!

Translation are not yet programmed. In theory in directory translation
(top level directory -to be created) you can put a *.ts file. This file
should include all words that are in QML files in the qsTr() function.
The structure should be like for this project of a friend:
https://kirgroup.com/projects/fabrixxm/friendly/master/translations.

Thank you!

**Comment by LubuWest** [comment]
Hi, there is a german translation file in the new version. You can use it as a template for spanish translation...

**Comment by LubuWest** [comment]
Spanish translation works! Thanks a lot.

**Comment by LubuWest** [comment]
Some texts are too long, but spanish translation works.

**Comment by susobaco** [comment]
I used abbreviations where they were. If you want, I can use more abbreviations
